---
- name: Create some Libvirt VM Shells
  hosts: all

  vars:
    templatingPath: /tmp/vms

    vms:
      - name: vbmh-user1-w1
        cpus: 4
        memory: 8
        disks:
          - name: boot
            size: 100
        networks:
          - name: bridge0
            networkType: bridge
      - name: vbmh-user1-w2
        cpus: 4
        memory: 8
        disks:
          - name: boot
            size: 100
        networks:
          - name: bridge0
            networkType: bridge

    vm_architecture: x86_64
    libvirt_host_os: fedora
    libvirt_firmware_mode: uefi
    libvirt_uri: qemu:///system

  tasks:
    - name: Create the templatingPath
      ansible.builtin.file:
        path: "{{ templatingPath }}"
        state: directory

    - name: Create the VMs
      ansible.builtin.include_tasks: vm_loop.yml
      loop: "{{ vms }}"
      loop_control:
        loop_var: v_item