---

- name: Template the VM XML
  ansible.builtin.template:
    src: templates/vm.xml.j2
    dest: "{{ templatingPath }}/{{ v_item.name }}.xml"

- name: Create the QCow2 disk locally when it does not exist
  ansible.builtin.command: "qemu-img create -f qcow2 -o preallocation=metadata,compat=1.1,lazy_refcounts=on {{ libvirt_base_vm_path | default('/var/lib/libvirt/images') }}/{{ v_item.name }}-{{ d_item.name }}.qcow2 {{ d_item.size }}G"
  args:
    creates: "{{ libvirt_base_vm_path | default('/var/lib/libvirt/images') }}/{{ v_item.name }}-{{ d_item.name }}.qcow2"
  loop: "{{ v_item.disks }}"
  loop_control:
    loop_var: d_item

- name: Define the VMs
  community.libvirt.virt:
    command: define
    xml: "{{ lookup('template', 'templates/vm.xml.j2') }}"
    #xml: "{{ templatingPath }}/{{ v_item.name }}.xml"
    uri: "{{ libvirt_uri }}"